// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjhBxsc3GSZRPFyS3lxNlFpZEz0c3VJeA',
    appId: '1:706570813689:web:65190306bfce6c1b9ee228',
    messagingSenderId: '706570813689',
    projectId: 'device-streaming-74b3b173',
    authDomain: 'device-streaming-74b3b173.firebaseapp.com',
    storageBucket: 'device-streaming-74b3b173.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtoHUw-OQv0QW60EpaDsmH2g1tLjJeBrk',
    appId: '1:706570813689:android:34264a2b4b1e35379ee228',
    messagingSenderId: '706570813689',
    projectId: 'device-streaming-74b3b173',
    storageBucket: 'device-streaming-74b3b173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTu2TCxzcYyWwOSXxoKNfmNrYSd8u529A',
    appId: '1:706570813689:ios:cbcac38925f15c9a9ee228',
    messagingSenderId: '706570813689',
    projectId: 'device-streaming-74b3b173',
    storageBucket: 'device-streaming-74b3b173.firebasestorage.app',
    iosBundleId: 'com.jhf.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTu2TCxzcYyWwOSXxoKNfmNrYSd8u529A',
    appId: '1:706570813689:ios:cbcac38925f15c9a9ee228',
    messagingSenderId: '706570813689',
    projectId: 'device-streaming-74b3b173',
    storageBucket: 'device-streaming-74b3b173.firebasestorage.app',
    iosBundleId: 'com.jhf.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjhBxsc3GSZRPFyS3lxNlFpZEz0c3VJeA',
    appId: '1:706570813689:web:c77c54b2296639869ee228',
    messagingSenderId: '706570813689',
    projectId: 'device-streaming-74b3b173',
    authDomain: 'device-streaming-74b3b173.firebaseapp.com',
    storageBucket: 'device-streaming-74b3b173.firebasestorage.app',
  );
}
